# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: dependency-checker@1
  inputs:
    path: '$(Build.SourcesDirectory)'
    searchRecursive: true
    combineProjects: false
    includePrerelease: false
    useArtifacts: false
    createBadge: false
    createReport: true
    reportPath: '$(Build.ArtifactStagingDirectory)\dependencies.html'